version: 2.1

orbs:
  aws-eks: circleci/aws-eks@1.1.0
  # can use an orb for kubernetes here!
  kubernetes: circleci/kubernetes@0.4.0

jobs:
  build-environment:
    docker:
      - image: python:3.7.3-stretch
    working_directory: ~/capstone

    steps:
      - checkout
      # Download and cache the dependencies 
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no match is found 
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
            # pylint here
            pip install pylint
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint
            
  build-and-deploy-docker-image:
    machine: true
    working_directory: ~/capstone
    steps:
      - checkout
      - run: 
          name: build, tag and push image
          command: |
            # the docker password is stored in circleci in the environment variables
            docker login -u jensmohmetui -p ${DOCKER_PASSWORD}
            # docker build
            docker build -t jensmohmetui/capstone .
            # docker push
            docker push jensmohmetui/capstone
            
  create-cluster:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
        
    steps:
      - run:
          name: Install the eksctl tool
          command: |
            if which eksctl > /dev/null; then
              echo "eksctl is installed already"
              exit 0
            fi
            mkdir -p eksctl_download
            curl --silent --location --retry 5 "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" \
              | tar xz -C eksctl_download
            chmod +x eksctl_download/eksctl
            SUDO=""
            if [ $(id -u) -ne 0 ] && which sudo > /dev/null ; then
              SUDO="sudo"
            fi
            $SUDO mv eksctl_download/eksctl /usr/local/bin/
            rmdir eksctl_download
            
      - aws-eks/create-cluster:
          cluster-name: eks-cluster
          aws-region: eu-central-1

  deploy-app-eks:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
      aws-region:
        description: |
          AWS region
        type: string 
    steps:
      - checkout
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          install-kubectl: true
          aws-region: eu-central-1
      - kubernetes/create-or-update-resource:
          get-rollout-status: true
          resource-file-path: "app-deployment.yaml"          
          resource-name: deployment/app
      - kubernetes/create-or-update-resource:
          resource-file-path: "app-service.yaml"
      - run:
          name: information
          command: |
            # some time for creation
            sleep 60
            kubectl get svc
            kubectl get nodes
            kubectl get deployment
            kubectl get pods -o wide
  delete-cluster:
      executor: aws-eks/python3
      parameters:
        cluster-name:
          description: |
            Name of the EKS cluster
          type: string
      steps:
        - run:
            name: Install the eksctl tool
            command: |
              if which eksctl > /dev/null; then
                echo "eksctl is already installed"
                exit 0
              fi
              mkdir -p eksctl_download
              curl --silent --location --retry 5 "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" \
                | tar xz -C eksctl_download
              chmod +x eksctl_download/eksctl
              SUDO=""
              if [ $(id -u) -ne 0 ] && which sudo > /dev/null ; then
                SUDO="sudo"
              fi
              $SUDO mv eksctl_download/eksctl /usr/local/bin/
              rmdir eksctl_download
              
        - aws-eks/delete-cluster:
            cluster-name: eks-cluster-mohme
            aws-region: eu-central-1
            wait: true

workflows:
  default:
    jobs:
      - build-environment
      - build-and-deploy-docker-image:
          requires: [build-environment]
      - create-cluster:
          requires: [build-and-deploy-docker-image]
          cluster-name: eks-cluster-mohme
      - deploy-app-eks:
          requires: [build-and-deploy-docker-image,create-cluster]
          cluster-name: eks-cluster-mohme
          aws-region: eu-central-1
      - delete-cluster:
          requires: [build-and-deploy-docker-image,create-cluster,deploy-app-eks]
          cluster-name: eks-cluster-mohme
          
